[workspace]
resolver = "2"
members = ["examples/*", "features/*", "strategies/*", "wrapp"]

[workspace.dependencies]

# Project Modules
wrapp-di = { path = "./features/wrapp-di" }

# External Crates
futures = "0.3"
futures-channel = "0.3"
tracing = "0.1"
pin-project-lite = "0.2"
thiserror = "2.0"
