[package]
name = "wrapp-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", optional = true }
axum = "0.8"
utoipa-axum = "0.2"
utoipa = "5.4.0"


[features]
default = ["tokio"]
tokio = ["dep:tokio"]
