[package]
name = "wrapp-di"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.31"
futures-channel = "0.3.31"
thiserror = "2.0.11"
tracing = "0.1.41"
