[package]
name = "wrapp-di"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures.workspace = true
futures-channel.workspace = true
tracing.workspace = true
pin-project-lite.workspace = true
thiserror.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true

[lints]
workspace = true
