//! # Wrapp DI
//!
//! Opinionated dependency injection framework for Wrapp.
//!
//! ### Overview
//! - [`DiBuilder`]: Main registration and building interface for the DI container.
//! - [`DiContainer`]: The DI container that holds instances and resolves dependencies.
//! - [`InstanceFactory`]: Trait for factories that can create instances of specific types. Usually
//!   generated by the `todo!()` proc macro.
//! - [`Resolver`]: Trait allowing implementation of custom resolution strategies.
//!
//! ### Example
//!
//! ```
#![doc = include_str!("../examples/manual-di-impl.rs")]
//! ```
//! 
//! ### Internal Flow
//!
//! - All dependencies are registered in the [`DiBuilder`] either as instances or factories.
//! - When [`DiBuilder::build`] is called, the [`DiInitiator`] is created.
//! - The [`DiInitiator`] creates a [`DependencyGraph`] from the registered dependencies, checking
//!   for circular dependencies and other issues.
//! - Afterwards all [`InstanceFactory`] are called and executed in a [`FuturesUnordered`], first to
//!   check if they are enabled, and then to create their instances.
//! - Results from the [`InstanceFactory`] are stored and become available through a handle to the
//!   [`DiInitiator`].
//! - After all factories have been called, all results are collected and stored in the
//!   [`DiContainer`], which is then returned to the application.
//!
//!
//! [`InstanceFactory`]: factories::InstanceFactory
//! [`DiBuilder`]: builder::DiBuilder
//! [`DiBuilder::build`]: builder::DiBuilder::build
//! [`DiInitiator`]: initiator::DiInitiator
//! [`DiContainer`]: container::DiContainer
//! [`DependencyGraph`]: dependency_graph::DependencyGraph
//! [`Resolver`]: resolver::Resolver
//! [`FuturesUnordered``]: futures::stream::FuturesUnordered

pub mod builder;
pub mod container;
pub mod dependency_graph;
pub mod errors;
pub mod factories;
pub mod initiator;
pub mod resolver;
pub mod types;
